---
title: "Integracion MC con reducion de varianza"
output: html_document
---

```{r replicabilidad}
set.seed(457367)
```

En esto caso quieremos que medir el tiempo utilizado por la generacion
```{r}
unidad_de_tiempo <- "ms"
```

## Montecarlo directo
```{r montecarlo-directo}
#generacion
genera_valor_aleatorio <- function(){
  runif(1)
}
#funcion
g <- function(x){
  (1-x^2)^(3/2)
}
#replicacion
n <- 1e4
coste_directo <- bench::mark({ #medir el tiempo
  valores <- replicate(n,{
    x <- genera_valor_aleatorio()
    g(x)
  })
}, 
iterations = 10,
time_unit = unidad_de_tiempo,
)$median
#estimacion
estimacion_directo <- mean(valores)
varianza_directo <- var(valores)/n

#eficiencia
eficiencia_directo <- 1/(varianza_directo*coste_directo)
```

## Muestro estratificado: asignacion proporcional
```{r}
library(ggplot2)

ggplot()+
  geom_function(fun = g) +
  xlim(0,1)
```
```{r generacion-proporcional}
estratos <- data.frame(
  extremo_izq = c(0, 1/4),
  extremo_der = c(1/4, 1),
  probabilidades = c(1/4, 3/4) #distribucion uniforme
)

genera_valor_aleatorio_en_estrato <- function(numero_estrato){
  estrato <- estratos[numero_estrato,]
  runif(1,
        min = estrato$extremo_izq,
        max = estrato$extremo_der)
}
```

```{r replicacion-proporcional}
n_estratos <- ceiling(n * estratos$probabilidades)
n_estratos <- pmax(0, n_estratos) #parallel max

cantidad_estrados <- nrow(estratos)

coste_estratificato_proporcional <- bench::mark(
  valores <- purrr::map2(
      seq_len(cantidad_estrados),
      n_estratos,
      \(numero_estrato, n_estrato){
        replicate(n_estrato, {
          x <- genera_valor_aleatorio_en_estrato(numero_estrato)
          g(x)
        })
      }
    ),
  iterations = 10,
  time_unit = unidad_de_tiempo
)$median
```

```{r estimacion-proporcional}
library(magrittr)

#estimacion
estimacion_estratificado_proporcional <- mean(unlist(valores)) #tenemos que desarrolar la lista

#varianza del estimador
varianza_estratificado_proporcional <- valores %>%
  purrr::map_dbl(var) %>%
  weighted.mean(w = estratos$probabilidades) %>%
  magrittr::divide_by(n)

#eficiencia
eficiencia_estratificado_proporcional <- 
  1/(varianza_estratificado_proporcional*coste_estratificato_proporcional)

```


## Tabla comparativa
```{r}
knitr::kable(
  data.frame(Metodo = c("Directo", 
                 "Estratificado con asignacion proporcional"),
    Estimacion = c(estimacion_directo, estimacion_estratificado_proporcional),
    Varianza = c(varianza_directo, varianza_estratificado_proporcional),
    Coste= c(coste_directo, coste_estratificato_proporcional),
    Eficiencia = c(eficiencia_directo, eficiencia_estratificado_proporcional),
  ),
  digits = 10
)
```


```{r replicacion}

```

```{r estimacion}

```



